sudo: required

services:
  - docker

env:
  matrix:
    - DOCKERFILE="Dockerfile-cli" DOCKERPATH="5.6"
    - DOCKERFILE="Dockerfile-apache" DOCKERPATH="5.6"
    - DOCKERFILE="Dockerfile-fpm" DOCKERPATH="5.6"
    - DOCKERFILE="Dockerfile-alpine-cli" DOCKERPATH="5.6"
    - DOCKERFILE="Dockerfile-alpine-fpm" DOCKERPATH="5.6"
    - DOCKERFILE="Dockerfile-cli" DOCKERPATH="7.0"
    - DOCKERFILE="Dockerfile-apache" DOCKERPATH="7.0"
    - DOCKERFILE="Dockerfile-fpm" DOCKERPATH="7.0"
    - DOCKERFILE="Dockerfile-alpine-cli" DOCKERPATH="7.0"
    - DOCKERFILE="Dockerfile-alpine-fpm" DOCKERPATH="7.0"
    - DOCKERFILE="Dockerfile-cli" DOCKERPATH="7.1"
    - DOCKERFILE="Dockerfile-apache" DOCKERPATH="7.1"
    - DOCKERFILE="Dockerfile-fpm" DOCKERPATH="7.1"
    - DOCKERFILE="Dockerfile-alpine-cli" DOCKERPATH="7.1"
    - DOCKERFILE="Dockerfile-alpine-fpm" DOCKERPATH="7.1"
    - DOCKERFILE="Dockerfile-cli" DOCKERPATH="7.2"
    - DOCKERFILE="Dockerfile-apache" DOCKERPATH="7.2"
    - DOCKERFILE="Dockerfile-fpm" DOCKERPATH="7.2"
    - DOCKERFILE="Dockerfile-alpine-cli" DOCKERPATH="7.2"
    - DOCKERFILE="Dockerfile-alpine-fpm" DOCKERPATH="7.2"

before_script:
  - docker version

script:
  - docker build -f ./${DOCKERPATH}/${DOCKERFILE} -t ${DOCKERPATH} ./${DOCKERPATH}

after_script:
  - docker images
  - docker run --rm -ti ${DOCKERPATH} php -i
