name: Build and push to registry
on:
  schedule:
    - cron: '0 7 * * *'
  push:
    branches:
      - dev-2.x

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        image_version:
          - "cli"
          - "fpm"
        php_version:
          - "5.6"
          - "7.0"
          - "7.1"
          - "7.2"
          - "7.3"
          - "7.4"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.php_version }}
          file: ./${{ matrix.php_version }}/Dockerfile-${{ matrix.image_version }}
          push: true
          tags: drupaldocker/php-dev:${{ matrix.php_version }}-${{ matrix.image_version }}-2.x
